name: "[Windows] MagicMirror² and MMM-Linky build Testing"

on: [pull_request]

jobs:
  build:
    name: Test install MMM-Linky
    runs-on: windows-latest
    strategy:
      matrix:
        node-version: [ 20.x ]
    steps:
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          check-latest: true

      - name: Checkout MagicMirror²
        uses: actions/checkout@v4
        with:
          repository: MagicMirrorOrg/MagicMirror

      - name: Install MagicMirror²
        run: npm install

      - name: Checkout MMM-Linky
        uses: actions/checkout@v4
        with:
          path: MagicMirror/modules/MMM-Linky

      - name: Install MMM-Linky
        run: npm run setup
        working-directory: MagicMirror/modules/MMM-Linky
        continue-on-error: false
